version: 2

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: products
        columns:
          - name: code
            tests:
              - not_null
              - unique
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: raw_products
        description: "Raw Canadian products from extraction"
