version: 2

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: raw_products
        description: "Raw Canadian products from extraction layer"
        columns:
          - name: code
            description: "Product barcode - Primary Key"
            tests:
              - not_null
              - unique
          - name: product_name
            description: "Product name"
          - name: brands
            description: "Brand name"
          - name: countries_tags
            description: "List of country tags"
          - name: data
            description: "Full JSON data"
